file:
  directory: D:/2024-02/download/greengram_ver2

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name : GreenGram_Ver2
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram_ver2
    username : root
    password : green502

  servlet:
    multipart:
      max-file-size: 15MB

  springdoc:
    swagger-ui:
      default-model-expand-depth: 10
      display-request-duration: true
      groups-order : asc
      operations-sorter: method
      path: /swagger
      tags-sorter: alpha
    cache:
      disabled: true