const:
  default-page-size: 20

file:
  directory: D:/2024-02/download/greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: gpwlsmsqkqhrhtjdrurdlsjanqkfmekrmqgkrh12sjansksvhrgkek234198afdajknqwernkjahdo9faerknqweriuiauvhaqwer8234kjdf98123klasd908f13kj98g


mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name : GreenGram_Ver3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram_ver3
    username : root
    password : green502

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB

  springdoc:
    swagger-ui:
      default-model-expand-depth: 10
      display-request-duration: true
      groups-order : asc
      operations-sorter: method
      path: /swagger
      tags-sorter: alpha
    cache:
      disabled: true